// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/whoami.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.91.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/whoami.ts
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in user's profile and role in Smart Class Scheduler.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [{ data: profile, error: profileError }, { data: roles, error: roleError }] = await Promise.all([
      supabase.from("profiles").select("full_name, email, created_at").eq("user_id", userId).maybeSingle(),
      supabase.from("user_roles").select("role").eq("user_id", userId)
    ]);
    if (profileError) throw new ToolError(profileError.message);
    if (roleError) throw new ToolError(roleError.message);
    const result = {
      user_id: userId,
      email: profile?.email ?? ctx.getUserEmail() ?? null,
      full_name: profile?.full_name ?? null,
      roles: (roles ?? []).map((r) => r.role)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-timetable.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";
var DAYS = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
var list_timetable_default = defineTool2({
  name: "list_timetable",
  title: "List timetable entries",
  description: "List scheduled classes with course, section, faculty, classroom and time slot. Optionally filter by day of week (0=Sunday..6=Saturday).",
  inputSchema: {
    day_of_week: z.number().int().min(0).max(6).optional().describe("0=Sunday .. 6=Saturday"),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ day_of_week, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError2("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("timetable_entries").select(
      "id, day_of_week, is_active, faculty:faculty_id(name, email), classroom:classroom_id(name, building), time_slot:time_slot_id(slot_number, start_time, end_time), section:section_id(name, course:course_id(code, name))"
    ).eq("is_active", true).order("day_of_week").limit(limit ?? 50);
    if (typeof day_of_week === "number") query = query.eq("day_of_week", day_of_week);
    const { data, error } = await query;
    if (error) throw new ToolError2(error.message);
    const entries = (data ?? []).map((row) => ({
      id: row.id,
      day: DAYS[row.day_of_week] ?? String(row.day_of_week),
      slot: row.time_slot ? { number: row.time_slot.slot_number, start: row.time_slot.start_time, end: row.time_slot.end_time } : null,
      course: row.section?.course ? `${row.section.course.code} \u2014 ${row.section.course.name}` : null,
      section: row.section?.name ?? null,
      faculty: row.faculty?.name ?? null,
      classroom: row.classroom ? `${row.classroom.name} (${row.classroom.building})` : null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(entries, null, 2) }],
      structuredContent: { entries }
    };
  }
});

// src/lib/mcp/tools/list-classrooms.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_classrooms_default = defineTool3({
  name: "list_classrooms",
  title: "List classrooms",
  description: "List classrooms with capacity, building and facilities. Optionally filter by availability and minimum capacity.",
  inputSchema: {
    only_available: z2.boolean().optional().describe("Return only classrooms marked available."),
    min_capacity: z2.number().int().min(1).optional().describe("Minimum seating capacity.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ only_available, min_capacity }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError3("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("classrooms").select("id, name, building, capacity, has_ac, has_projector, is_available").order("building").order("name");
    if (only_available) query = query.eq("is_available", true);
    if (typeof min_capacity === "number") query = query.gte("capacity", min_capacity);
    const { data, error } = await query;
    if (error) throw new ToolError3(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { classrooms: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-faculty.ts
import { defineTool as defineTool4, ToolError as ToolError4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_faculty_default = defineTool4({
  name: "list_faculty",
  title: "List faculty",
  description: "List faculty members with department, designation, specialization and availability.",
  inputSchema: {
    search: z3.string().optional().describe("Filter by name or email substring."),
    only_available: z3.boolean().optional().describe("Return only faculty marked available.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, only_available }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError4("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("faculty").select("id, name, email, designation, specialization, is_available, department:department_id(code, name)").order("name");
    if (only_available) query = query.eq("is_available", true);
    if (search?.trim()) query = query.or(`name.ilike.%${search.trim()}%,email.ilike.%${search.trim()}%`);
    const { data, error } = await query;
    if (error) throw new ToolError4(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { faculty: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-courses.ts
import { defineTool as defineTool5, ToolError as ToolError5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_courses_default = defineTool5({
  name: "list_courses",
  title: "List courses and sections",
  description: "List courses with department, credits, semester and their sections.",
  inputSchema: {
    semester: z4.number().int().min(1).max(12).optional().describe("Filter by semester number."),
    search: z4.string().optional().describe("Filter by course code or name substring.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ semester, search }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError5("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("courses").select(
      "id, code, name, credits, semester, department:department_id(code, name), sections(id, name, max_students, faculty:faculty_id(name))"
    ).order("code");
    if (typeof semester === "number") query = query.eq("semester", semester);
    if (search?.trim()) query = query.or(`code.ilike.%${search.trim()}%,name.ilike.%${search.trim()}%`);
    const { data, error } = await query;
    if (error) throw new ToolError5(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { courses: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-absences.ts
import { defineTool as defineTool6, ToolError as ToolError6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var list_absences_default = defineTool6({
  name: "list_absences",
  title: "List faculty absences",
  description: "List recorded faculty absences with substitute assignment and processing status.",
  inputSchema: {
    from_date: z5.string().optional().describe("Only absences on or after this date (YYYY-MM-DD)."),
    to_date: z5.string().optional().describe("Only absences on or before this date (YYYY-MM-DD).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from_date, to_date }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError6("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("faculty_absences").select(
      "id, absence_date, reason, is_processed, faculty:faculty_id(name, email), substitute:substitute_faculty_id(name, email)"
    ).order("absence_date", { ascending: false }).limit(100);
    if (from_date) query = query.gte("absence_date", from_date);
    if (to_date) query = query.lte("absence_date", to_date);
    const { data, error } = await query;
    if (error) throw new ToolError6(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { absences: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/report-absence.ts
import { defineTool as defineTool7, ToolError as ToolError7 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^3.25.76";
var report_absence_default = defineTool7({
  name: "report_absence",
  title: "Report an absence",
  description: "Record an absence for the signed-in faculty member on a given date so the scheduler can reallocate their classes.",
  inputSchema: {
    absence_date: z6.string().describe("Date of the absence in YYYY-MM-DD format."),
    reason: z6.string().optional().describe("Short reason for the absence.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ absence_date, reason }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError7("Not authenticated");
    if (!/^\d{4}-\d{2}-\d{2}$/.test(absence_date)) throw new ToolError7("absence_date must be YYYY-MM-DD");
    const supabase = supabaseForUser(ctx);
    const { data: faculty, error: facultyError } = await supabase.from("faculty").select("id, name").eq("user_id", ctx.getUserId()).maybeSingle();
    if (facultyError) throw new ToolError7(facultyError.message);
    if (!faculty) throw new ToolError7("No faculty record is linked to your account, so an absence cannot be reported.");
    const { data, error } = await supabase.from("faculty_absences").insert({ faculty_id: faculty.id, absence_date, reason: reason ?? null }).select("id, absence_date, reason, is_processed").maybeSingle();
    if (error) throw new ToolError7(error.message);
    return {
      content: [
        { type: "text", text: `Absence recorded for ${faculty.name} on ${absence_date}.` }
      ],
      structuredContent: { absence: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "mrfgfufkfzlenatoxdpo";
var mcp_default = defineMcp({
  name: "smart-class-scheduler",
  title: "Smart Class Scheduler",
  version: "0.1.0",
  instructions: "Tools for Smart Class Scheduler, a university timetable and classroom allocation app. Use `whoami` to check the signed-in user's role, `list_timetable` for scheduled classes, `list_classrooms`, `list_faculty`, `list_courses` and `list_absences` for resources, and `report_absence` to record an absence for the signed-in faculty member. All data access respects the app's per-user permissions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    list_timetable_default,
    list_classrooms_default,
    list_faculty_default,
    list_courses_default,
    list_absences_default,
    report_absence_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
